import esbuild from "esbuild";
import process from "process";

const prod = process.argv[2] === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, visit the plugin repository.
*/
`;

const shared = {
	banner: { js: banner },
	entryPoints: ["main.ts"],
	bundle: true,
	jsx: "automatic",
	loader: {
		".tsx": "tsx",
		".jsx": "jsx",
	},
	external: [
		"obsidian",
		"child_process",
		"path",
		"fs",
		"os",
		"util",
		"stream",
		"crypto",
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
};

if (prod) {
	await esbuild.build(shared).catch(() => process.exit(1));
} else {
	const ctx = await esbuild.context(shared);
	await ctx.watch();
}
