import type { GzhWritingPipelineSettings } from "../types";
import { DEFAULT_WECHAT_SIMPLE_COVER_TAGLINE } from "../services/WechatSimpleCoverService";
import {
	DEFAULT_AUTHOR_PROFILE,
	DEFAULT_DRAFT_PROMPT,
	DEFAULT_HUMANIZE_PROMPT,
	DEFAULT_OUTLINE_PROMPT,
	DEFAULT_REVIEW_PROMPT,
	DEFAULT_VIDEO_SCRIPT_PROMPT,
	DEFAULT_WRITING_STYLE,
} from "../templates/defaultPrompts";

export const DEFAULT_SETTINGS: GzhWritingPipelineSettings = {
	provider: "openai",
	openai: {
		apiKey: "",
		baseUrl: "https://api.openai.com/v1",
		model: "gpt-4.1-mini",
	},
	deepseek: {
		apiKey: "",
		baseUrl: "https://api.deepseek.com",
		model: "deepseek-chat",
	},
	doubao: {
		apiKey: "",
		baseUrl: "",
		model: "",
	},
	publishedDirName: "Published",
	createPublishedUnderSourceDir: true,
	fixedPublishedDirPath: "",
	authorProfilePrompt: DEFAULT_AUTHOR_PROFILE,
	writingStylePrompt: DEFAULT_WRITING_STYLE,
	outlinePrompt: DEFAULT_OUTLINE_PROMPT,
	draftPrompt: DEFAULT_DRAFT_PROMPT,
	humanizePrompt: DEFAULT_HUMANIZE_PROMPT,
	reviewPrompt: DEFAULT_REVIEW_PROMPT,
	modelTemperature: 0.7,
	maxTokens: 4096,
	confirmBeforeOverwrite: true,
	keepHistoryVersions: false,
	enableDebugLog: false,

	wechatPublishMethod: "api",
	wechatTheme: "default",
	wechatColor: "",
	wechatAuthor: "",
	wechatAppId: "",
	wechatAppSecret: "",
	wechatSimpleCoverEnabled: true,
	wechatSimpleCoverBgId: "warm_cream",
	wechatSimpleCoverTagline: DEFAULT_WECHAT_SIMPLE_COVER_TAGLINE,
	wechatSimpleCoverLogoVaultPath: "",
	wechatRaphaelThemeId: "wechat",

	imageGenerationsUrl: "",
	imageModel: "gpt-image-1",
	imageSizeWechatCover: "",
	imageSizeWechatIllustration: "",
	imageSizeXhsCover: "",
	imageSizeXhsBody: "",
	imagePresetProvider: "gpt_image",
	imageApiKeyDoubaoArk: "",
	imageApiKeyZhipuGlm: "",
	imageApiKeyGptImage: "",
	useLlmApiKeyForImages: false,
	imageApiKey: "",

	mokaCardsDefaultPlatform: "xhs",
	mokaCardTemplateXhs: "cream_soft",
	mokaCardPaletteXhs: "coral",
	mokaCardTemplateWechat: "biz_pro",
	mokaCardPaletteWechat: "bluestone",
	mokaCardSizeWxH: "",
	mokaCardExportPixelRatio: 3,
	mokaCardSlideCount: 6,

	videoScriptPrompt: DEFAULT_VIDEO_SCRIPT_PROMPT,
	videoPythonPath: "python3",
	videoFfmpegPath: "",
	videoTtsEngine: "listenhub",
	listenhubApiKey: "",
	listenhubBaseUrl: "",
	listenhubVoice: "CN-Man-Beijing-V2",
	listenhubModel: "flowtts",
	videoBackgroundMusicPath: "",
	videoBackgroundMusicVolume: 0.14,
	videoOpenSec: 2.5,
	videoEndSec: 3.5,
};
